### ISSUE TITLE
Reported Challenge - space in account name breaks syntax

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette-backend#1031]
See https://github.com/maproulette/challenge-reports/issues/9

**Comment by matkoniecz** [comment]
Should be https://www.openstreetmap.org/user/Mateusz%20Konieczny - ` ` must be escaped

**Comment by ljdelight** [comment]
Thank you for the report! Closing this backend issue and created a FE issue here https://github.com/maproulette/maproulette3/issues/2183
