### ISSUE TITLE
Harness against Crypto deprecation

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette-backend#294]
Seeing 

`object Crypto in package libs is deprecated: This class is deprecated and will be removed in future versions`

during compile, we should probably update to be ready for this deprecation. [Seems to be a non-trivial change](https://www.playframework.com/documentation/2.5.x/CryptoMigration25).

**Comment by ljdelight** [comment]
The latest builds have no match for 'Crypto' in the log, and there's no imports for the reference crypto libs. It looks like this was resolved and can be closed. However there are references to using SHA1 on the message digests, so that could be improved, but it's not critical.
