### ISSUE TITLE
Your example for adding a quest does not work

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [maproulette/maproulette-backend#322]
It responds: `KO : ColumnName(.location,Some(location))`

**Comment by mvexel** [comment]
Which example are you referring to, please? How can I help?

**Comment by matkoniecz** [comment]
https://github.com/maproulette/maproulette2/wiki/Introducing-New-MapRoulette---Part-1.-Creating-and-Maintaining-Challenges#via-overpass

I tried copy-pasting this exact query as I run into problems described in #337 #335

On selecting view action from project menu I get "KO : ColumnName(.location,Some(location))" message flashing in a red box.

**Comment by mgcuthbert** [comment]
This is currently resolved, please check again to see if you continue to have any issues.
