### ISSUE TITLE
status: failed without any feedback

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette-backend#335]
My challenge http://maproulette.org/ui/admin/list/1986/Challenge/tasks/2747 has status failed.

Geojson is

```
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[8.5306777,11.9908895]},"properties":{"name": "\"Kofar Nassarawa\"", "name_1": "\"Badalar Kano\"", "source": "\"www.steadfast.com.ng\"", "historic": "\"monument\"", "source_1": "\"http://kanostreetsonosm.org.ng/\"", "wikipedia": "\"en:Kano City Walls and Gate\"", "description": "\"One of ancient Kano City Walls and Gate\""}}]}
```

produced by

```
[out:json];
(
way["wikipedia"="en:Kano City Walls and Gate"]
node["wikipedia"="en:Kano City Walls and Gate"]
); out body geom qt;
```

There is no feedback anywhere why status is failed.

From looking at http://maproulette.org/view/2747 there are no signs what went wrong.

**Comment by mvexel** [comment]
That is annoying and something I am looking to improve. Let me see if I can reproduce your case and help out.

**Comment by ljdelight** [comment]
Closing old ticket. UI will show errors at this point, and that geojson imported fine
