### ISSUE TITLE
Project challenges listing method issue

### ISSUE THREAD

**Issue by tBeata-grab** [maproulette/maproulette-backend#431]
The project challenges listing method does not work properly with pagination. The same result is returned in different order for different page numbers.
Example: 
     http://maproulette.org/api/v2/project/62/challenges?page=0&limit=1000 
     http://maproulette.org/api/v2/project/62/challenges?page=1&limit=1000

**Comment by ljdelight** [comment]
I checked and see that pagination is working, closing this old issue
