### ISSUE TITLE
Not able to install activator on Windows

### ISSUE THREAD

**Issue by cbeddow** [maproulette/maproulette-backend#459]
Going off this gist: https://gist.github.com/mvexel/3710d7f15534ec747423a3117cd7cc9c

I can't find where exactly I can get activator and install it, nor find the bin to add to path. 

Looking here: https://developer.lightbend.com/start/

I installed Scala. Should I install play instead?

Right now running `start.bat` gives me `'activator' is not recognized as an internal or external command, operable program, or batch file`

**Comment by ljdelight** [comment]
The maproulette-backend readme was updated recently with detailed setup instructions, generic enough for Windows/Mac/Linux platforms. Closing this issue
