### ISSUE TITLE
rename to `maproulette-backend` and move to osmlab

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette-backend#524]
let's move this repo to `osmlab` where `maproulette3` also lives, and rename it to `maproulette-backend` to indicate that this is (only) the backend for the MapRoulette application.

There are some preconditions for doing this, such as but not limited to adapting the deployment scripts.

**Comment by mvexel** [comment]
Let's do this :)

**Comment by ljdelight** [comment]
Renamed as `maproulette/maproulette-backend` :tada:
