### ISSUE TITLE
routing issue

### ISSUE THREAD

**Issue by gvoltz** [maproulette/maproulette-backend#526]
Could someone help me with an issue i'm encountering, while attempting to run maproulette2?

I'm attempting to run maproulette2 and maproulette3 locally. I have maproulette3 in good shape, but when I go to sign in I get the following response
{"status":"KO","message":"Communication with the service provider failed: Service provider responded in error: 301 (Moved Permanently)"}

I go to the URL (localhost:9000) of maproulette2 and get an ACTION NOT FOUND response as shown below. Aren't those paths meant to be built at the time of running with sbt? Is there a configuration that I'd need to change to resolve this?

If it helps to know...
I've tried with both activator & sbt, but get the same result 
    activator version: 1.3.12
    sbt version: 1.2.8
OS: Centos7.6
play version: 2.7.0
web browser: chrome
![image](https://user-images.githubusercontent.com/47166887/55163897-016aa080-5141-11e9-8df2-7a6c9ded828d.png)

**Comment by mgcuthbert** [comment]
So the reason this is happening is because maproulette2 (The API) doesn't actually have any routes on the root path, ie. "/". The reason for this is that maproulette is purely an API server, it has no UI anymore. This was a change that was recently made. 

So if you have maproulette3 (The Frontend) up and running on using the default port then you should be able to access the UI using "http://localhost:3000/" 

It would seem you have everything actually up and running and so hitting that local address should work.

**Comment by gvoltz** [comment]
Thanks for responding!

Yes, I see the frontend UI, but when I click the sign in button I'm redirected to the url that I set as the environment variable `REACT_APP_SERVER_OAUTH_URL=http://127.0.0.1:9000/auth/authenticate?redirect=http://127.0.0.1:3000`. I found this on the page instructions https://github.com/osmlab/maproulette3#developing-with-a-local-back-end-server

This is what I see after clicking the sign-in button. I'm using the OSM dev server and double checked my oauth keys too.
![image](https://user-images.githubusercontent.com/47166887/55253346-7b775400-522b-11e9-8571-bb398be42ee5.png)


When I unset the environment variable REACT_APP_SERVER_OAUTH_URL, I see the following after clicking the sign-in button.
![image](https://user-images.githubusercontent.com/47166887/55253747-8aaad180-522c-11e9-8432-7b5c6b831579.png)

I noticed the URL, after unsetting REACT_APP_SERVER_OAUTH_URL, mentions mr3. I looked over the maproulette dev instructions again, because mr3 rang a bell. I then entered the following at the end of the application.conf, but got the same 404 response.
![image](https://user-images.githubusercontent.com/47166887/55254097-66032980-522d-11e9-80f1-145c50df4ded.png)

**Comment by gvoltz** [comment]
disregard the last part about the addition to the application.conf file, that breaks the backend because it's a json parsing error.

**Comment by mgcuthbert** [comment]
Ok so I think those docs are a little out of date, as recently some of that stuff changed. Firstly the "mr3" keys in the application.conf file in the backed are deprecated. It won't hurt to have them in the file, but they aren't used anymore, so you don't have to worry about them. As for the values in your environment file, try using the following:
```
REACT_APP_URL='http://127.0.0.1:3000'
REACT_APP_MAP_ROULETTE_SERVER_URL='http://127.0.0.1:9000'
```

That should work, and those docs should be updated.

**Comment by mgcuthbert** [comment]
@nrotstan could you update those docs.

**Comment by nrotstan** [comment]
Sorry about that, @gvoltz, PR osmlab/maproulette3#708 will remove from the README any mention of those old backend configuration options that are no longer needed.

For now, you can view that updated README at https://github.com/osmlab/maproulette3/blob/706afc7363742ad6345f0aff711bea37e8507d76/README.md

Let me know if you continue to have issues.

**Comment by gvoltz** [comment]
Thanks for the info. Unfortunately that didn't resolve my issue, but I believe it got me a step closer. I now see the backend returning the following error.

![image](https://user-images.githubusercontent.com/47166887/55650672-69119300-57b4-11e9-81f0-5ad242f15048.png)

**Comment by ljdelight** [comment]
We've update the `README.md` to include great detail on how to do the initial project setup, and includes validation steps along the way. 

Closing this issue and see #998 for import steps
