### ISSUE TITLE
Getting empty 200 response with no data

### ISSUE THREAD

**Issue by tori-bird** [maproulette/maproulette-backend#844]
I'm trying to work with the API on a separately running instance of MapRoulette. I am using the provided url and auth key, however when I try to get a response with data all that is returned is the status code. I've tried this with both requests and the maproulette API wrapper package. Can you tell me why this might happen for any call I try to make to the API?

**Comment by nrotstan** [comment]
Hi @tori-bird , I haven't experienced that before. Can you provide more detail about the actual requests you're making? Are you using the API key provided to your user, or one you setup in the conf file? And I assume you have data on the server to return?

Try this: login to your MR instance and then navigate your browser to the *backend server* (on port 9000 by default) /api/v2/user/whoami (e.g. `http://127.0.0.1:9000/api/v2/user/whoami`). Do you see data?

Then if that works, go to the User Settings page and note the API key at the bottom of the page and try hitting the server with curl, passing `-H "apiKey: yourAPIKeyHere"` to include your API key in the request header, e.g.: `curl -H "apiKey: yourAPIKeyHere" http://127.0.0.1:9000/api/v2/user/whoami` and see if that works. If it does, then your API key is correct and working. If you get something like "Authorization failed" then your API key is incorrect -- double check it, and if necessary you can even reset it from the User Settings page to get a fresh one.

**Comment by ljdelight** [comment]
Closing, this is an old ticket. It's not clear what would cause all APIs to not be sending response payloads, and there's insufficient information to look further.
